# Generated by Django 4.2.1 on 2023-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligiaroupas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
