# Generated by Django 4.1 on 2023-06-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('ligiaroupas', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Produto',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
