# Generated by Django 4.2.1 on 2023-05-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('ligiaroupas', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
