# Generated by Django 4.1 on 2023-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligiaroupas', '0003_rename_item_produto_alter_produto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenscompra',
            old_name='item',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='itenscompra',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
